<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';

$client = new \Github\Client(
    new \Github\HttpClient\CachedHttpClient(array('cache_dir' => './data/github-api-cache'))
);

$nick = $_REQUEST['user'];
if (! $nick) {
  $nick = 'deiu';
}

$user = $client->api('user')->show($nick);


$users = $client->api('user')->following('melvincarvalho');

echo "<h3>Profile</h3>";
echo "<div>$user[login]</div>";
echo "<div>$user[name]</div>";
echo "<div>$user[blog]</div>";
echo "<div><img src='$user[avatar_url]'/>";

echo "<h3>Followers</h3>";
for($i=0; $i<sizeof($users); $i++) {
  $login = $users[$i]['login'];
  echo "<div><a href='user.php?user=$login'>$login</a></div>";
}


?>
